application:
  port: 8000
  hmac_secret: "8{F]5<]y7iep'c.+mbQT(A9&=:FWJ\"~Mu#:qH()wHC&rze&zYyuO\".VPI}n{V9e"
database:
  host: "localhost"
  port: 5432
  username: "postgres"
  password: "password"
  database_name: "newsletter"
  require_ssl: true
email_client:
  base_url: "http://localhost/"
  sender_email: "zero2prod@avandesa.dev"
  authorization_token: "POSTMARK_API_TEST"
  timeout_millis: 10000
